name: 'Cypress report action'
description: 'Basic report added to the pull request as a comment with summary and detailed failures table using github actions.'
icon: alert-triangle
color: green
inputs:
  token:
    description: "Github token"
    required: true
  pathname:
    description: 'Full pathname to the mochawesome report JSON file'
    required: true
    default: 'test/'
  title:
    description: "Title in the comment"
    default: "## :evergreen_tree: Cypress report"
    required: false
  always:
    description: 'Should it be shown always or it should be deleted when there are no failures'
    required: false
    default: true
  pr:
    description: 'The PR number. If not specified, will try to use `github.context.issue.number`.'
    required: false
    default: null
runs:
  using: 'node12'
  main: 'dist/index.js'
